# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LagoonSync < Formula
  desc "Lagoon's development sync tool"
  homepage "https://github.com/tobybellwood/lagoon-sync"
  version "0.7.0-rc.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-sync/releases/download/v0.7.0-rc.1/lagoon-sync_0.7.0-rc.1_darwin_amd64.tar.gz"
      sha256 "ed7b2fb5e11c3015659edab2f8e99e5db69976009d514d2546292ee71798d24a"

      def install
        bin.install "lagoon-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobybellwood/lagoon-sync/releases/download/v0.7.0-rc.1/lagoon-sync_0.7.0-rc.1_darwin_arm64.tar.gz"
      sha256 "313ca2c99caf11436839eaa9532b5e8d82a2f034083ab4a6ab60c036bec12867"

      def install
        bin.install "lagoon-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobybellwood/lagoon-sync/releases/download/v0.7.0-rc.1/lagoon-sync_0.7.0-rc.1_linux_arm64.tar.gz"
      sha256 "46dc6d9df09114c3bd01259cf097a9aafe0c8685a17630359a315ec38666ad46"

      def install
        bin.install "lagoon-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tobybellwood/lagoon-sync/releases/download/v0.7.0-rc.1/lagoon-sync_0.7.0-rc.1_linux_amd64.tar.gz"
      sha256 "be1c7a6aaa1fa4978caa110bc20d4f603b99f641487b93079b0b487f54b7172c"

      def install
        bin.install "lagoon-sync"
      end
    end
  end

  test do
    system "#{bin}/lagoon-sync version"
  end
end
